import type { NewsItem, WorkspaceState } from './types';

const now = '2026-09-08T09:00:00+09:00';

export const seedState: WorkspaceState = {
  members: [
    {
      id: 'han',
      name: '한지원',
      email: 'admin@local.test',
      role: 'admin',
      team: '파크사업팀',
      active: true,
    },
    {
      id: 'kim',
      name: '김민석',
      email: 'member@local.test',
      role: 'member',
      team: '파크사업팀',
      active: true,
    },
    {
      id: 'ceo',
      name: '대표님',
      email: 'viewer@local.test',
      role: 'commenter',
      team: '경영진',
      active: true,
    },
  ],
  categories: [
    { id: 'park', name: '파크운영', color: '#4f8a6d', active: true },
    { id: 'sales', name: '영업·제휴', color: '#547da8', active: true },
    { id: 'external', name: '대외협력', color: '#9b6caf', active: true },
    { id: 'data', name: '데이터관리', color: '#8468ad', active: true },
    { id: 'system', name: '시스템관리', color: '#d58b45', active: true },
    { id: 'cs', name: 'CS·SNS', color: '#cc6b61', active: true },
  ],
  tasks: [
    {
      id: 'task-1',
      title: '주간 VOC 취합',
      description: '카카오채널, 대표메일, 현장 CS를 한 번에 정리합니다.',
      date: '2026-09-08',
      categoryId: 'cs',
      assigneeId: 'kim',
      collaborators: ['han'],
      priority: 'normal',
      status: 'in_progress',
      type: 'routine',
      checklist: [
        { id: 'c1', text: '채널별 문의 수 집계', done: true },
        { id: 'c2', text: '반복 이슈 분류', done: false },
      ],
      comments: [],
      createdBy: 'han',
      createdAt: now,
    },
    {
      id: 'task-2',
      title: '가을 프로그램 현장 동선 검토',
      description: '우천 시 대체 동선과 안내 위치를 함께 검토합니다.',
      date: '2026-09-15',
      endDate: '2026-09-15',
      categoryId: 'park',
      assigneeId: 'han',
      collaborators: ['kim'],
      priority: 'urgent',
      status: 'scheduled',
      type: 'event',
      checklist: [
        { id: 'c3', text: '혼잡 구간 확인', done: false },
        { id: 'c4', text: '우천 대안 작성', done: false },
      ],
      comments: [],
      createdBy: 'han',
      createdAt: now,
    },
    {
      id: 'task-3',
      title: 'OTA 채널 정보 점검',
      description: '운영시간과 판매 상품 정보를 확인합니다.',
      date: '2026-09-09',
      categoryId: 'sales',
      assigneeId: 'kim',
      collaborators: [],
      priority: 'normal',
      status: 'scheduled',
      type: 'routine',
      checklist: [],
      comments: [],
      createdBy: 'han',
      createdAt: now,
    },
    {
      id: 'task-4',
      title: '시설 조치 최종 확인',
      description: '야외 안내판 고정 상태를 현장에서 확인합니다.',
      date: '2026-09-07',
      categoryId: 'park',
      assigneeId: 'kim',
      collaborators: [],
      priority: 'urgent',
      status: 'completion_requested',
      type: 'issue',
      checklist: [{ id: 'c5', text: '현장 사진 확인', done: true }],
      comments: [
        {
          id: 'm1',
          authorId: 'kim',
          body: '조치 완료했습니다. 최종 확인 부탁드립니다.',
          createdAt: now,
        },
      ],
      createdBy: 'han',
      createdAt: now,
    },
    {
      id: 'task-5',
      title: '입장객·매출 자료 정리',
      description: '8월 입장객과 매출 데이터를 취합합니다.',
      date: '2026-09-11',
      categoryId: 'data',
      assigneeId: 'kim',
      collaborators: ['han'],
      priority: 'normal',
      status: 'scheduled',
      type: 'task',
      checklist: [],
      comments: [],
      createdBy: 'han',
      createdAt: now,
    },
  ],
  routines: [
    {
      id: 'routine-1',
      title: '주간 VOC 취합',
      categoryId: 'cs',
      assigneeId: 'kim',
      cadence: '매주 화요일',
      checklist: ['채널별 문의 수 집계', '반복 이슈 분류', '공유 메모 작성'],
      referenceUrl: '',
      active: true,
      nextDate: '2026-09-15',
    },
    {
      id: 'routine-2',
      title: '월간 입장객·매출 정리',
      categoryId: 'data',
      assigneeId: 'kim',
      cadence: '매월 첫 영업일',
      checklist: ['입장객 집계', '매출 집계', '전년 대비 확인'],
      referenceUrl: '',
      active: true,
      nextDate: '2026-10-01',
    },
    {
      id: 'routine-3',
      title: 'OTA 판매 정보 점검',
      categoryId: 'sales',
      assigneeId: 'han',
      cadence: '격주 수요일',
      checklist: ['운영시간 확인', '상품 가격 확인'],
      referenceUrl: '',
      active: true,
      nextDate: '2026-09-16',
    },
  ],
  notes: [
    {
      id: 'note-1',
      label: '특이사항-20260908-001',
      date: '2026-09-08',
      categoryId: 'park',
      location: '야외가든',
      body: '오후 강풍 예보로 야외 프로그램 운영 여부 확인 필요',
      urgent: true,
      createdBy: 'kim',
      createdAt: now,
    },
  ],
};

export const seedNews: NewsItem[] = [
  {
    id: 'news-1',
    title: '제주 가을 관광 프로그램 확대',
    category: '제주관광',
    source: '관광뉴스 수집 문서',
    collectedAt: '2026-09-08',
  },
  {
    id: 'news-2',
    title: '지역 관광시설 안전점검 강화',
    category: '제주 관광지 방문객 수',
    source: '관광뉴스 수집 문서',
    collectedAt: '2026-09-07',
  },
];
